/** @file 44.cpp Problem 44: Pentagon numbers
 *
 * Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten
 * pentagonal numbers are:
 *
 *      1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 *
 * It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
 * 70 - 22 = 48, is not pentagonal.
 *
 * Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
 * difference are pentagonal and D = |Pk - Pj| is minimised; what is the value
 * of D?
 */

// The delta between consecutive pentagonals grows monotonically, so minimizing
// the distance |Pk - Pj| just means choosing the lowest values that satisfy
// the requirements.

#include "monotonic.hpp"    // pentagonal_src, pentagonal_set

/// @cond
#include <cstdint>          // uint64_t
#include <iostream>         // cout
/// @endcond

using std::uint64_t;

using src = monotonic::pentagonal_src<uint64_t>;
using set = monotonic::pentagonal_set<uint64_t>;

int main()
{
    uint64_t d = 0;
    set set;
    src ys;
    ys.next();
    for (uint64_t y = ys.next(); !d ; y = ys.next()) {
        src xs;
        for (uint64_t x = xs.next(); !d && x < y; x = xs.next()) {
            if (set[x + y] && set[y - x])
                d = y - x;
        }
    }
    std::cout << d << std::endl;
}
